### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-code-comments-plugin#53]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by nb** [comment]
Hey, @rjollos.

Thanks for the suggestion. For now we would prefer to leave the plugin in this organization, because it makes permissions and collaborations easier (all colleagues get automatically added to a group where they have access).

If we decide to stop maintaining it, we will definitely look for a new home at `trac-hacks`.

**Comment by rjollos** [comment]
Thanks for the reply. There isn't any activity with the plugin for more than 2 years and some issues need to be fixed. Is there a way I can help get fixes merged?

The plugin also needs some work to be compatible with Trac 1.2 and later.
