### ISSUE TITLE
URL Not found

### ISSUE THREAD

**Issue by dbapl** [trac-hacks/trac-code-comments-plugin#56]
When master is installed on server witch multiple Trac environments, plugin tries to access URL:
https://trac.example.com/subscription/trac/project/browser
Trac project is on URL:
https://trac.example.com/trac/project/
so it will never hit Trac environment.

The same will happen with one Trac environment not installed on domain root. For example when Subversion and Trac work on the same server/domain this plugin will be unusable.

**Comment by nb** [comment]
Hey, @esyscoder, in what cases do you see this URL? I can't reproduce it, so I will need more details and possibly steps to reproduce the problem. Thanks!

**Comment by dbapl** [comment]
For example when I go to changset page, I see JS alert "Not found", because JS is trying to go to URL I mentioned.
To reporoduce install Trac in subdirectory not on the root of the server.

The code that makes this bug is in code-comments.js:

```
  window.Subscription = Backbone.Model.extend({
    url: '/subscription' + location.pathname,
  });
```

It gives always root of the server but Trac can be in subdirectory.
