### ISSUE TITLE
this plugin wipes out jQuery and $, and causes problem with other trac plugins

### ISSUE THREAD

**Issue by walty8** [trac-hacks/trac-code-comments-plugin#79]
In the last line of `htdocs/code-comments/code-comments.js`, there is `jQuery.noConflict( true ) `. And according to the [documentation](https://api.jquery.com/jquery.noconflict/), this actually wipes out all globally existing `jQuery` variables, which was loaded in the trac core. This causes immediate problems with other jQuery dependent plugins like  [trac-readme-plugin](https://github.com/trac-hacks/trac-readme-plugin).

Simply change to `}); }( jQuery.noConflict( ) ) );` seems to fix the problem.

**Comment by rjollos** [comment]
Thanks, @walty8. Would you mind submitting a pull request?
